# Generated by Django 3.0.5 on 2020-06-28 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summerApp', '0002_auto_20200628_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sumemrphoto',
            name='photo',
            field=models.ImageField(blank=True, upload_to='image'),
        ),
    ]
